### PR TITLE
fix: the projectName should not be `.` in README if created in current directory

### PR DESCRIPTION
**Pull request by btea**

### CODE REVIEW

**Comment by sodatea** [comment]
There's no such bug. Because when the user passes `.` to the command line, the `projectName` prompt will be skipped; therefore `result.projectName` will be `undefined`.

**Comment by btea** [comment]
The `projectName` prompt doesn't seem to be skipped when the user enters `.`, so the value of `projectName` is `.`. Therefore, the title in README is `.`.
image

**Comment by sodatea** [comment]
I can't reproduce it

**Comment by btea** [comment]
Follow the steps shown in the figure to reproduce
image

Maybe it's related to the system environment, I'm using windows 🤔

**Comment by sodatea** [comment]
😂 You explicitly used `.` as the project **name**…
It's a name, not a path. I don't expect people to use it this way.

The way to create the project in the current directory should be `pnpm create vue@3 .`

**Comment by btea** [comment]
🤣 Embarrassing, I always use this to create projects in the current folder.

**Pull request closed without merging**
