### PR TITLE
chore: remove unused parameter

### PR DESCRIPTION
**Pull request by btea**

### CODE REVIEW

**Review by cexbrayat — COMMENTED** [review]
Good catch, but maybe the proper fix is to use the parameter to generate the readme?

**Comment by btea** [comment]
Makes sense, but I'm not sure what the generated content based on the `needsNightwatchCT` parameter should be?

**Comment by cexbrayat** [comment]
I think `needsNightwatch` is used twice, instead I think it should be `needsNightwatchCT` here https://github.com/vuejs/create-vue/pull/448/files#diff-a4daf76507373a095f626fff68f5cecaa33d5d10a4dbca6aaad95ef30a80bd30R125

**Comment by btea** [comment]
Okay, I have made the modifications.

**Review by cexbrayat — APPROVED** [review]

**Pull request merged**
