### PR TITLE
Default open page.

### PR DESCRIPTION
**Pull request by zhangenming**
I think it's a useful feature...

### CODE REVIEW

**Comment by linghengqian** [comment]
I don't think so.  At least this is false in webpack devserver, which can cause confusion for newbies migrating to vite.

**Comment by zhangenming** [comment]
how about add it, but let it be comment. serve as a reminder
For me, I didn't even know about it until a long time ago

**Comment by linghengqian** [comment]
> how about add it, but let it be comment. serve as a reminder
> For me, I didn't even know about it until a long time ago

I just thought, this is actually what vite's documentation mentions.  This is not a reasonable tip.

**Comment by btea** [comment]
Vite already supports the shortcut key `o` to open in the browser. Therefore, I think this is unnecessary.

**Pull request closed without merging**
