### PR TITLE
fix: created vue2 project ts error

### LINKED ISSUE #370: pnpm create vue@legacy or pnpm create vue@2 error warning
I use the command pnpm create vue@2 to build the vue2+vite+js project. I did not select ts. Why does the component show lang=ts?
There are also a proliferation of commands to build vue projects, vue create my-vue-app, pnpm create my-app-vue, pnpm create vue@2, pnpm create vue@3, (pnpm create vite official website says this), What are the differences between these different commands? Are these different build commands officially maintained? Why are there so many different build commands? Feeling illegally confused and confused as to which one should be used.
vite+vue2
goujian
Related code:

[https://github.com/vuejs/create-vue/blob/v2/template/code/router/src/views/HomeView.vue#L1](url)

### PR DESCRIPTION
**Pull request by btea**
fix #370

### CODE REVIEW

**Review by cexbrayat — APPROVED** [review]
@btea You need to rebase the PR, otherwise LGTM

**Comment by btea** [comment]
Sorry, I don't know how to rebase in this case, can you give me a hint? Thanks! 🤦‍♂️

**Comment by cexbrayat** [comment]
I suppose you can do (assuming `upstream` is the `vuejs/create-vue` repo):

```
git checkout fix/component-ts-error
git fetch upstream
git rebase upstream/v2
# solve conflicts
git rebase continue
git push origin fix/component-ts-error --force
```

Does that help?

**Comment by btea** [comment]
@cexbrayat It has been solved, thank you very much! 👍

**Review by cexbrayat — APPROVED** [review]

**Pull request merged**
