### PR TITLE
fix: use child_process module to create project

### PR DESCRIPTION
**Pull request by btea**
### Description

The following error will occur on Windows platform when executing `pnpm snapshot`.

QQ_1723075297659

### CODE REVIEW

**Review by cexbrayat — COMMENTED** [review]
I'm not sure we should change this. `zx` is explicit about having to use bash even on Windows (see https://google.github.io/zx/setup#bash).

**Comment by btea** [comment]
Yeah, I noticed this too. However, the default terminal launched by vscode is not bash, and it needs to be switched manually, which seems a bit troublesome. Or, is there any other way to use base to run files by default? 🤔

**Comment by cexbrayat** [comment]
@btea I don't know how you can switch on VS Code, but I guess there is a way to define your default terminal. Let's close then

**Comment by btea** [comment]
I found that we use `npm-run-all2`, but I think we can directly replace it with `pnpm run build && pnpm run snapshot`, maybe we can remove this dependency. What do you think? @cexbrayat 
https://github.com/vuejs/create-vue/blob/f283ab4fdc0cbef48e8ecde77d52f2398540e08d/package.json#L23

**Comment by cexbrayat** [comment]
@btea Sure, why not

**Pull request closed without merging**
